# Configuration for weekly-digest - https://github.com/apps/weekly-digest
publishDay: thursday
canPublishIssues: true
canPublishPullRequests: true
canPublishContributors: false
canPublishStargazers: false
canPublishCommits: false
